points:
  - id: 0
    angles:
      straight: 45.0
      diverging: 135.0
      default: 45.0
  - id: 1
    angles:
      straight: 45.0
      diverging: 135.0
      default: 45.0
  - id: 2
    angles:
      straight: 45.0
      diverging: 135.0
      default: 45.0
  - id: 3
    angles:
      straight: 45.0
      diverging: 135.0
      default: 45.0
  - id: 4
    angles:
      straight: 45.0
      diverging: 135.0
      default: 45.0
  - id: 5
    angles:
      straight: 45.0
      diverging: 135.0
      default: 45.0
  - id: 6
    angles:
      straight: 45.0
      diverging: 135.0
      default: 45.0
  - id: 7
    angles:
      straight: 45.0
      diverging: 135.0
      default: 45.0
  - id: 8
    angles:
      straight: 45.0
      diverging: 135.0
      default: 45.0
