points:
  - id: 0
    angles:
      straight: 60.0
      diverging: 107.0
      default: 60.0
  - id: 1
    angles:
      straight: 45.0
      diverging: 95.0
      default: 45.0
  - id: 2
    angles:
      straight: 100.0
      diverging: 55.0
      default: 100.0
  - id: 3
    angles:
      straight: 50.0
      diverging: 100.0
      default: 50.0
  - id: 4
    angles:
      straight: 110.0
      diverging: 60.0
      default: 110.0
  - id: 5
    angles:
      straight: 50.0
      diverging: 110.0
      default: 50.0
  - id: 6
    angles:
      straight: 120.0
      diverging: 50.0
      default: 50.0
  - id: 7
    angles:
      straight: 120.0
      diverging: 60.0
      default: 120.0
